---
apiVersion: v1
kind: Pod
metadata:
    name: fortune-pod
    labels: 
        app: fortune
spec:
    containers:
    - name: fortune-container
      image: tanchunwei/fcookie:v2
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 3000
