---
apiVersion: v1
kind: Namespace
metadata: 
  name: fortune-ns
  labels: 
    app: fortune
    version: v1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  namespace: fortune-ns
  labels:
    app: fortune
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fortune-pod
  template: 
    metadata:
      name: fortune-pod
      labels: 
        app: fortune-pod
    spec:
      containers:
      - name: fortune-container
        image: tanchunwei/fcookie:v2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: fortune-svc
  namespace: fortune-ns
  labels:
    apps: fortune
spec: 
  type: LoadBalancer
  selector: 
    app: fortune-pod
  ports:
  - port: 80
    targetPort: 3000 