---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwapp-cm
  labels:
    app: northwind
data:
  DB_USER: root
  DB_HOST: nwdb-svc.nw.svc.cluster.local #FQDN (if in same namespace can just use service name)
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwapp-deploy
  labels:
    app: northwind
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nwapp-pod
  template: 
    metadata:
      name: nwapp-pod
      labels: 
        app: nwapp-pod
    spec:
      containers:
      - name: nwapp-container
        image: tanchunwei/nwapp:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: nw-secret
              key: MYSQL_ROOT_PASSWORD
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef: 
              fieldPath: status.podIP
        envFrom:
          - configMapRef: 
              name: nwapp-cm
        ports:
        - name: nwapp-port
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata: 
  name: nwapp-svc
  labels:
    app: northwind
spec:
  type: LoadBalancer
  selector:
    app: nwapp-pod
  ports:
  - port: 80
    targetPort: nwapp-port

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nwapp-ing
  labels:
    app: northwind
spec:
  rules: 
  - host: nwapp.167.172.6.228.nip.io
    http: 
      paths:
      - path: /
        backend: 
          serviceName: nwapp-svc
          servicePort: 80