apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: nwdb-pvc
  labels: 
    app: northwind
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi