controller:
  publishService:
    enabled: true
    
defaultBackend:
  enabled: true
  image:
    repository: chukmunnlee/ingress_default_backend #repository: nginx/nginx-ingress
    tag: v1 #tag: latest
  port: 3000